subscription.vnet.aks.cluster.class: aks
subscription.vnet.aks.cluster.label: ${name}-AKS-Cluster
subscription.vnet.aks.cluster.grid-columns: 2
subscription.vnet.aks.cluster.grid-rows: 3
subscription.vnet.aks.cluster.grid-gap: 3

subscription.vnet.aks.cluster.lin1.class: aks_nodepool
subscription.vnet.aks.cluster.lin1.label: ${name}-Lin1-Node-Pool

subscription.vnet.aks.cluster.win1.class: aks_nodepool
subscription.vnet.aks.cluster.win1.label: ${name}-Win1-Node-Pool

subscription.vnet.aks.cluster.system.class: aks_nodepool
subscription.vnet.aks.cluster.system.label: ${name}-System-Node-Pool

subscription.vnet.aks.cluster.lin2.class: aks_nodepool
subscription.vnet.aks.cluster.lin2.label: ${name}-Lin2-Node-Pool

subscription.vnet.aks.cluster.win2.class: aks_nodepool
subscription.vnet.aks.cluster.win2.label: ${name}-Win2-Node-Pool

