classes: {
    subscription: {
        ...@container_style
        icon: https://raw.githubusercontent.com/benc-uk/icon-collection/master/azure-icons/Subscriptions.svg
        style {
            fill: "#FFE6CC"
        }

    }
    virtual_network: {
        ...@container_style
        icon: https://raw.githubusercontent.com/benc-uk/icon-collection/master/azure-icons/Virtual-Networks.svg
        style {
            fill: "#D5E8D4"
        }
    }
    subnet: {
        ...@container_style
        # icon: https://raw.githubusercontent.com/benc-uk/icon-collection/master/azure-icons/Subnet.svg
        icon: https://raw.githubusercontent.com/benc-uk/icon-collection/master/azure-icons/Virtual-Networks.svg
        style {
            fill: "#DAE8FC"
        }
    }
    aks: {
        ...@container_style
        icon: https://raw.githubusercontent.com/benc-uk/icon-collection/master/azure-icons/Kubernetes-Services.svg
        style {
            fill: "#E1D5E7"
        }
    }
}

classes: {
    invisible: {
        shape: none
        style: {
            opacity: 0
        }
        label: "fill"
    }
    route_table: {
        ...@icon_style
        icon: https://raw.githubusercontent.com/benc-uk/icon-collection/master/azure-icons/Route-Tables.svg
    }
    network_security_group: {
        ...@icon_style
        icon: https://raw.githubusercontent.com/benc-uk/icon-collection/master/azure-icons/Network-Security-Groups.svg
    }
    aks_nodepool: {
        ...@icon_style
        icon: https://raw.githubusercontent.com/benc-uk/icon-collection/master/azure-icons/VM-Scale-Sets.svg
    }
    virtual_machine: {
        ...@icon_style
        icon: https://raw.githubusercontent.com/benc-uk/icon-collection/master/azure-icons/Virtual-Machine.svg
    }
    sql_virtual_machine: {
        ...@icon_style
        icon: https://raw.githubusercontent.com/benc-uk/icon-collection/master/azure-icons/Azure-SQL-VM.svg
    }
    key_vault: {
        ...@icon_style
        icon: https://raw.githubusercontent.com/benc-uk/icon-collection/master/azure-icons/Key-Vaults.svg
    }
    storage_account: {
        ...@icon_style
        icon: https://raw.githubusercontent.com/benc-uk/icon-collection/master/azure-icons/Storage-Accounts.svg
    }
    azure_files: {
        ...@icon_style
        icon: https://raw.githubusercontent.com/benc-uk/icon-collection/master/azure-icons/Azure-Fileshares.svg
    }
}